/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareCircleRouteImport } from './routes/care-circle'
import { Route as CareNetworkRouteImport } from './routes/care-network'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as MyVoiceRouteImport } from './routes/my-voice'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as CareSummaryPersonIdRouteImport } from './routes/care-summary.$personId'
import { Route as VoiceGuestPersonIdRouteImport } from './routes/voice-guest.$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareCircleRoute = CareCircleRouteImport.update({
  id: '/care-circle',
  path: '/care-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CareNetworkRoute = CareNetworkRouteImport.update({
  id: '/care-network',
  path: '/care-network',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyVoiceRoute = MyVoiceRouteImport.update({
  id: '/my-voice',
  path: '/my-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const CareSummaryPersonIdRoute = CareSummaryPersonIdRouteImport.update({
  id: '/care-summary/$personId',
  path: '/care-summary/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceGuestPersonIdRoute = VoiceGuestPersonIdRouteImport.update({
  id: '/voice-guest/$personId',
  path: '/voice-guest/$personId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care-circle': typeof CareCircleRoute
  '/care-network': typeof CareNetworkRoute
  '/check-in': typeof CheckInRoute
  '/moments': typeof MomentsRoute
  '/my-voice': typeof MyVoiceRoute
  '/people': typeof PeopleRoute
  '/care-summary/$personId': typeof CareSummaryPersonIdRoute
  '/voice-guest/$personId': typeof VoiceGuestPersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care-circle': typeof CareCircleRoute
  '/care-network': typeof CareNetworkRoute
  '/check-in': typeof CheckInRoute
  '/moments': typeof MomentsRoute
  '/my-voice': typeof MyVoiceRoute
  '/people': typeof PeopleRoute
  '/care-summary/$personId': typeof CareSummaryPersonIdRoute
  '/voice-guest/$personId': typeof VoiceGuestPersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care-circle': typeof CareCircleRoute
  '/care-network': typeof CareNetworkRoute
  '/check-in': typeof CheckInRoute
  '/moments': typeof MomentsRoute
  '/my-voice': typeof MyVoiceRoute
  '/people': typeof PeopleRoute
  '/care-summary/$personId': typeof CareSummaryPersonIdRoute
  '/voice-guest/$personId': typeof VoiceGuestPersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care-circle'
    | '/care-network'
    | '/check-in'
    | '/moments'
    | '/my-voice'
    | '/people'
    | '/care-summary/$personId'
    | '/voice-guest/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care-circle'
    | '/care-network'
    | '/check-in'
    | '/moments'
    | '/my-voice'
    | '/people'
    | '/care-summary/$personId'
    | '/voice-guest/$personId'
  id:
    | '__root__'
    | '/'
    | '/care-circle'
    | '/care-network'
    | '/check-in'
    | '/moments'
    | '/my-voice'
    | '/people'
    | '/care-summary/$personId'
    | '/voice-guest/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareCircleRoute: typeof CareCircleRoute
  CareNetworkRoute: typeof CareNetworkRoute
  CheckInRoute: typeof CheckInRoute
  MomentsRoute: typeof MomentsRoute
  MyVoiceRoute: typeof MyVoiceRoute
  PeopleRoute: typeof PeopleRoute
  CareSummaryPersonIdRoute: typeof CareSummaryPersonIdRoute
  VoiceGuestPersonIdRoute: typeof VoiceGuestPersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-circle': {
      id: '/care-circle'
      path: '/care-circle'
      fullPath: '/care-circle'
      preLoaderRoute: typeof CareCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-network': {
      id: '/care-network'
      path: '/care-network'
      fullPath: '/care-network'
      preLoaderRoute: typeof CareNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-voice': {
      id: '/my-voice'
      path: '/my-voice'
      fullPath: '/my-voice'
      preLoaderRoute: typeof MyVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-summary/$personId': {
      id: '/care-summary/$personId'
      path: '/care-summary/$personId'
      fullPath: '/care-summary/$personId'
      preLoaderRoute: typeof CareSummaryPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-guest/$personId': {
      id: '/voice-guest/$personId'
      path: '/voice-guest/$personId'
      fullPath: '/voice-guest/$personId'
      preLoaderRoute: typeof VoiceGuestPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareCircleRoute: CareCircleRoute,
  CareNetworkRoute: CareNetworkRoute,
  CheckInRoute: CheckInRoute,
  MomentsRoute: MomentsRoute,
  MyVoiceRoute: MyVoiceRoute,
  PeopleRoute: PeopleRoute,
  CareSummaryPersonIdRoute: CareSummaryPersonIdRoute,
  VoiceGuestPersonIdRoute: VoiceGuestPersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
